export const oblasts = [
  {id: 'ciua21glebrkckb2', label: 'Autonomous Republic of Crimea_Автономна Республіка Крим'},
  {id: 'chvmygrlebrkckc3', label: 'Cherkaska_Черкаська'},
  {id: 'clo1x4vlebrkckc4', label: 'Chernihivska_Чернігівська'},
  {id: 'ctohs39lebrkckc5', label: 'Chernivetska_Чернівецька'},
  {id: 'c247whblebrkckc6', label: 'Dnipropetrovska_Дніпропетровська'},
  {id: 'cdqzkfalebrkckc7', label: 'Donetska_Донецька'},
  {id: 'ci6107klebrkckc8', label: 'Ivano-Frankivska_Івано-Франківська'},
  {id: 'c4s5fm0lebrkckc9', label: 'Kharkivska_Харківська'},
  {id: 'c7f3g3ilebrkckda', label: 'Khersonska_Херсонська'},
  {id: 'cuup1d8lebrkckdb', label: 'Khmelnytska_Хмельницька'},
  {id: 'c3uihhnlebrkckdc', label: 'Kirovohradska_Кіровоградська'},
  {id: 'c1tv3frlebrkckdd', label: 'Kyiv_Київ'},
  {id: 'coi9q1zlebrkckde', label: 'Kyivska_Київська'},
  {id: 'cfje7n6lebrkckdf', label: 'Luhanska_Луганська'},
  {id: 'cm6px6xlebrkckdg', label: 'Lvivska_Львівська'},
  {id: 'ctv8cw5lebrkckdh', label: 'Mykolaivska_Миколаївська'},
  {id: 'c23ovtglebrkckdi', label: 'Odeska_Одеська'},
  {id: 'ciiv648lebrkckdj', label: 'Poltavska_Полтавська'},
  {id: 'chadf69lebrkckdk', label: 'Rivnenska_Рівненська'},
  {id: 'c27kgk0lebrkckdl', label: 'Sevastopol_Севастополь'},
  {id: 'cj530slebrkckdm', label: 'Sumska_Сумська'},
  {id: 'cx73u5ulebrkckdn', label: 'Ternopilska_Тернопільська'},
  {id: 'cb1bqpilebrkckdo', label: 'Vinnytska_Вінницька'},
  {id: 'cnf4ddvlebrkckdp', label: 'Volynska_Волинська'},
  {id: 'cesrf15lebrkckdq', label: 'Zakarpatska_Закарпатська'},
  {id: 'cez5t8mlebrkckdr', label: 'Zaporizka_Запорізька'},
  {id: 'cyx8240lebrkckds', label: 'Zhytomyrska_Житомирська'}
]
