import {MPCA_NFI_MykoOptions} from './MPCA_NFI_MykoOptions'

type Opt<T extends keyof typeof MPCA_NFI_MykoOptions> = keyof (typeof MPCA_NFI_MykoOptions)[T]

export interface MPCA_NFI_Myko {
start: string | undefined,
	end: string | undefined,
	today: string | undefined,
	Is_this_beneficiary_a_patient_at_a_ward: string | undefined,
	location_geopoint: string | undefined,
	consent_mod_1: Opt<'consent_mod_1'> | undefined,
	patron: string | undefined,
	name_resp: string | undefined,
	last_resp: string | undefined,
	phone: number | undefined,
	Does_the_beneficiary_have_an_i: Opt<'Does_the_beneficiary_have_an_i'> | undefined,
	Other_ID_identification: Opt<'Other_ID_identification'> | undefined,
	Number_of_ID: string | undefined,
	ITN: string | undefined,
	Total_Family: number | undefined,
	AgeHH: number | undefined,
	GenderHH: Opt<'GenderHH'> | undefined,
	Kits_to_be_provided: Opt<'Kits_to_be_provided'> | undefined,
	HKMV_: number | undefined,
	HKF_: number | undefined,
	BLN_: number | undefined,
	WKB1_How_many: number | undefined,
	WKB2_How_many: number | undefined,
	WKB3_How_many: number | undefined,
	WKB4_How_many: number | undefined,
	BK1_How_many: number | undefined,
	BK2_How_many: number | undefined,
	BK3_How_many: number | undefined,
	BK4_How_many: number | undefined,
	consent_signature_payment: string | undefined,
}