import {Enum} from '@alexandreannic/ts-utils'

export const oblastByIso = {
  'UA71': 'Cherkaska',
  'UA74': 'Chernihivska',
  'UA77': 'Chernivetska',
  'UA12': 'Dnipropetrovska',
  'UA14': 'Donetska',
  'UA26': 'Ivano-Frankivska',
  'UA63': 'Kharkivska',
  'UA65': 'Khersonska',
  'UA68': 'Khmelnytska',
  'UA35': 'Kirovonhradska',
  'UA32': 'Kyivska',
  'UA09': 'Luhanska',
  'UA46': 'Lvivska',
  'UA48': 'Mykolaivska',
  'UA51': 'Odeska',
  'UA53': 'Poltavska',
  'UA56': 'Rivenska',
  'UA40': 'Sevastopilska',
  'UA59': 'Sumska',
  'UA61': 'Ternopilska',
  'UA05': 'Vinnytska',
  'UA07': 'Volynska',
  'UA21': 'Zakarpatska',
  'UA23': 'Zaporizka',
  'UA18': 'Zhytomyrska',
  'UA43': 'Avtonomna Respublika Krym',
}
export const oblastISOByName = {
  'Cherkaska': 'UA71',
  'Chernihivska': 'UA74',
  'Chernivetska': 'UA77',
  'Dnipropetrovska': 'UA12',
  'Donetska': 'UA14',
  'Ivano-Frankivska': 'UA26',
  'Kharkivska': 'UA63',
  'Khersonska': 'UA65',
  'Khmelnytska': 'UA68',
  'Kirovonhradska': 'UA35',
  'Kyivska': 'UA32',
  'Luhanska': 'UA09',
  'Lvivska': 'UA46',
  'Mykolaivska': 'UA48',
  'Odeska': 'UA51',
  'Poltavska': 'UA53',
  'Rivenska': 'UA56',
  'Sevastopilska': 'UA40',
  'Sumska': 'UA59',
  'Ternopilska': 'UA61',
  'Vinnytska': 'UA05',
  'Volynska': 'UA07',
  'Zakarpatska': 'UA21',
  'Zaporizka': 'UA23',
  'Zhytomyrska': 'UA18',
  'Avtonomna Respublika Krym': 'UA43',
}
